---
title: "cleaning_description"
author: "Elle Holbrook"
date: "11/5/2017"
output: word_document
---

```{r}
clean_yearly_person_file <- function(year) {
# 1. Read data in.
person_file <- paste0("data-raw/yearly_person_data/person_", year, ".csv")
df <- readr::read_csv(person_file)
# 2. Convert all column names to lowercase.
colnames(df) <- tolower(colnames(df))
df <- df %>%
# 3. Limit variables.
dplyr::select(st_case, veh_no, per_no, state, per_typ, lag_hrs, lag_mins,
inj_sev, age, alc_res, contains("drugres"), sex) %>%
# 4. Limit to relevant `per_typ` and `inj_sev` values, then remove those variables.
dplyr::filter(per_typ == 1 & inj_sev == 4) %>%
dplyr::select(-per_typ, -inj_sev) %>%
# 5. Create a `unique_id`. Note: to be unique, `year` needs to be pasted on.
tidyr::unite(unique_id, st_case, veh_no, per_no) %>%
dplyr::mutate(year = year,
unique_id = paste(unique_id, year, sep = "_")) %>%
# 6. Limit to study states and then remove the `state` variable.
dplyr::filter(state %in% c(6,
15,
17,
33,
44,
54)) %>%
dplyr::select(-state) %>%
# 7. Convert `sex` to a factor with levels "Male" and "Female".
dplyr::mutate(sex = ifelse(sex == 9, NA, sex),
sex = factor(sex, levels = c(1, 2),
labels = c("Male", "Female"))) %>%
# 8. Use measured alcohol blood level to create `Alcohol` (logical for whether
# alcohol was present). Then remove the `alc_res` variable.
dplyr::mutate(alc_res = ifelse(alc_res > 94, NA, alc_res / 10),
Alcohol = alc_res >= 0.01) %>%
dplyr::select(-alc_res) %>%
# 9. Specify missing values for the lag minutes.
dplyr::mutate(lag_mins = ifelse(lag_mins == 99, NA, lag_mins))
# 10. Save lag hours coded as missing as `NA`.
if(year <= 2008){
df <- df %>%
dplyr::mutate(lag_hrs = ifelse(lag_hrs %in% c(99, 999), NA, lag_hrs))
} else {
df <- df %>%
dplyr::mutate(lag_hrs = ifelse(lag_hrs == 999, NA, lag_hrs))
}
# 11. Limit to deaths within an hour of the accident then remove those variables.
df <- df %>%
dplyr::filter((lag_hrs < 1) | (lag_hrs == 1 & lag_mins == 0)) %>%
dplyr::select(-lag_hrs, -lag_mins)
# 12. Save age values coded as missing as `NA`.
if(year <= 2008){
df <- df %>%
dplyr::mutate(age = ifelse(age == 99, NA, age))
} else {
df <- df %>%
dplyr::mutate(age = ifelse(age %in% c(998, 999), NA, age))
}
# 13. Use age to create age categories and then remove `age` variable.
df <- df %>%
dplyr::mutate(agecat = cut(age, breaks = c(0, 25, 45, 65, 1000),
labels = c("< 25 years",
"25--44 years",
"45--64 years",
"65 years +"),
include.lowest = TRUE, right = FALSE)) %>%
dplyr::select(-age)
# 14. Gather all the columns with different drug listings (i.e., `drugres1`,
# `drugres2`, `drugres3`). Convert from the numeric code listings to
# drug categories.
gathered_df <- df %>%
tidyr::gather(drug_number, drug_type_raw, contains("drugres")) %>%
dplyr::mutate(drug_type = ifelse(drug_type_raw %in% 100:295,
"Narcotic", NA),
drug_type = ifelse(drug_type_raw %in% 300:395,
"Depressant", drug_type),
drug_type = ifelse(drug_type_raw %in% 400:495,
"Stimulant", drug_type),
drug_type = ifelse(drug_type_raw %in% 600:695,
"Cannabinoid", drug_type),
drug_type = ifelse(drug_type_raw %in% c(500:595, 700:996),
"Other", drug_type),
drug_type = ifelse(drug_type_raw == 1,
"None", drug_type),
drug_type = factor(drug_type)) %>%
dplyr::select(-drug_type_raw, -drug_number) %>%
# 15. Filter out any observations where both alcohol and drug data is missing.
dplyr::filter(!(is.na(Alcohol) & is.na(drug_type)))
# 16. Create a subset with only individuals with at least one non-missing
# listing for drugs. (Write a sentence or two for each step in this pipe chain.)
non_missing_drugs <- gathered_df %>%
filter(!is.na(drug_type)) %>%
group_by(unique_id, drug_type) %>%
summarize(has_drug = TRUE) %>%
  ungroup() %>%
mutate(row_num = 1:n()) %>%
spread(drug_type, has_drug, fill = FALSE) %>%
select(-row_num)
# 17. Join this back into the full dataset. (Write a sentence or two for each
# step in this pipe chain.)
df <- df %>%
dplyr::select(-contains("drugres")) %>%
dplyr::full_join(non_missing_drugs, by = "unique_id") %>%
dplyr::select(-None) %>%
tidyr::gather(drug_type, positive_for_drug, Alcohol, Cannabinoid,
Depressant, Narcotic, Other, Stimulant) %>%
dplyr::mutate(drug_type = factor(drug_type)) %>%
unique()
return(df)
}
# 18. Iterate the clean_yearly_person_file function across study years to
# create and save a single dataset.
# Note: map_df() is similar to map(), but it binds elements of the
# list resulting from map() together. To understand this step, try
# running this code with map instead of map_df, check out documentation
# for map and map_df, and look at the map_df() function by typing
# `map_df` in your console.
clean_fars <- map_df(1999:2010, clean_yearly_person_file)
save(clean_fars, file = "data/clean_fars.RData")
```

# Cleaning steps descriptions:
1. Read in the data using a relative pathname to the data-raw subdirectory. Allows for reading in all person_year.csv files at once by allowing for variation in the 4-digit year.

2. The `tolower` function from `base` R allows us to change the characters in a string to all lowercase. This is desirable in order to comply with the style guidelines and make the column headers/variable names easier to work with in our coding.

3. Using the `select` function lets us keep only the variables of interest for our analysis. This just makes it easier to work with a dataframe so you don't have a bunch of extraneous information that you won't actually end up using, but doesn't require you to remove those variables from the original dataset.

4. In this analysis we only want to look at drivers who died in their respective car crashes, so limiting to `per_type == 1` and `inj_sev == 4` removes accidents for which these criteria don't apply. Since we limit the dataframe to only include the driver and fatal crashes, we can then remove these variables from the dataframe because we know that all remaining observations meet the criteria we're interested in.

5. Here we `unite` three different columns to create a unique identifier for each observation. In order for each of these IDs to be unique, the new ID column must combine `st_case`, `per_no` and `veh_no` along with the year. By uniting these 4 pieces of information, we can create a new column, `unique_id` to identify each unit of observation in one column rather than 3 columns within separate spreadsheets.

6. As in step 3, we only want to look at data from certain states. We can limit our dataframe to only include those states and then remove the `state` column in order to exclude extraneous and unnecessary information.

7. The FARS dataset uses numerical coding for `sex` so we need to change it to a factor. It also uses a number for unknown values of `sex` by using the number 9. In this step, we use the `ifelse` function to tell R to look for instances where `sex == 9` (unknown). If this is true, replace with an NA. If this is not true, use the value of `sex`, either "Male" or "Female."

8. We also want to create a column that indicates the presence or absence of alcohol in a crash event. Using the `ifelse` function again, we can recode missing values by telling R to look for instances where the `alc_res` column has above a certain value (94) and mark those as NAs; if this condition isn't met, use the value from the column divided by 10. We can then put this information into a new column, `Alcohol`, which will indicate a decimal value of blood alcohol content greater than 0.01. Once we have this new column, we can remove the `alc_res` column.

9. The `lag_mins` column is another that contains numerically-coded missing values. We once again use the `ifelse` function to change a lag value of 99 to NA. If the `lag_mins` value is not 99, we'd like to keep it for use in the analysis.

10. Similar to our previous uses of the `ifelse` function, the `lag_hrs` column also has missing data that needs to be converted to NAs. However, the encoding method for missing values in this column changed between 2008 and 2009. So here we tell R to look for `lag_hrs` equal to 99 or 999 up to 2008 and equal to 999 in 2009 and later.

11. 







