---
title: "fars_analysis"
author: "Elle Holbrook"
date: "11/5/2017"
output: pdf_document
---
```{r messages = FALSE, warnings = FALSE}
library(tidyverse)
library(ggthemes)

load("../data/clean_fars.RData")
source("../R/fars_functions.R")
```



```{r}
clean_fars %>%
  mutate(year_cat = cut(year, breaks = c(1999, 2002, 2006, 2010),
                        labels = c("1999-2002", "2003-2006",
                                   "2007-2010"),
                        include.lowest = TRUE, right = TRUE)) %>%
  filter(!is.na(sex)) %>%
  group_by(drug_type, sex, year_cat) %>%
  summarize(n_non_missing = sum(!is.na(positive_for_drug)),
            positive_test = sum(positive_for_drug, na.rm = TRUE),
            perc_positive = round(100 * positive_test / n_non_missing, 1)) %>%
  select(drug_type, sex, year_cat, perc_positive) %>%
  unite(sex_year_cat, sex, year_cat) %>%
  spread(sex_year_cat, perc_positive) %>%
  knitr::kable(col.names = c("Drug type", "F 1999-2002",
                             "F 2003-2006", "F 2007-2010",
                             "M 1999-2002", "M 2003-2006",
                             "M 2007-2010"))
```

```{r recreating figure 1}
fig1_data <- clean_fars %>% 
  filter(!drug_type == "Alcohol",
         !is.na(positive_for_drug),
         !is.na(agecat)) %>% 
  select(unique_id, drug_type, year, agecat, positive_for_drug) %>% 
  group_by(year, agecat, unique_id) %>% 
  summarize(positive = any(positive_for_drug)) %>% 
  ungroup() %>% 
  group_by(year, agecat) %>% 
  summarize(perc = 100 * mean(positive))

fig1_data %>% 
  ggplot(aes(x = year, y = perc)) +
  geom_line(aes(linetype = agecat)) +
  labs(x = "Year", 
       y = "Positive for nonalcohol drugs, %",
       linetype = "Age") +
  ggtitle("Figure 1: Prevalence of nonalcohol drugs in fatally injured 
          drivers by year and age group") +
  theme_few()
```

```{r recreating figure 2}
fig2_data <- clean_fars %>% 
  filter(!drug_type == "Alcohol",
         !is.na(positive_for_drug)) %>%
  select(unique_id, drug_type, year, positive_for_drug) %>% 
  group_by(year, drug_type, unique_id) %>% 
  summarize(positive = any(positive_for_drug)) %>% 
  ungroup() %>% 
  group_by(year, drug_type) %>% 
  summarize(perc = 100 * mean(positive))
  
fig2_data %>% 
  ggplot(aes(x = year, y = perc)) +
  geom_line(aes(linetype = drug_type)) +
  labs(x = "Year",
       y = "Positive for Drugs, %",
       linetype = "Drug type") +
  ggtitle("Figure 2: Prevalence of nonalcohol drugs in fatally injured 
          drivers by year and drug type") +
  theme_few()
```

```{r recreating figure 3}
fig3_data <- clean_fars %>% 
  filter(drug_type == "Cannabinoid",
         !is.na(positive_for_drug),
         !is.na(agecat)) %>% 
  select(unique_id, drug_type, agecat, year, positive_for_drug) %>% 
  group_by(year, unique_id, agecat) %>% 
  summarize(positive = any(positive_for_drug)) %>% 
  ungroup() %>% 
  group_by(year, agecat) %>% 
  summarize(perc = 100 * mean(positive))

fig3_data %>% 
  ggplot(aes(x = year, y = perc)) +
  geom_line(aes(linetype = agecat)) +
  labs(x = "Year",
       y = "Positive for Cannabinoid, %",
       linetype = "Age") +
  ggtitle("Figure 3: Prevalence of cannabinoid drugs in fatally injured 
          drivers by year and age group") +
  theme_few()
```

